- name: installing mongodb
  hosts: mongodb
  become: yes

  tasks:
  - name: Install MongoDB
    ansible.builtin.copy:
     src: mongodb.repo
     dest: /etc/yum.repos.d/mongodb.repo

  - name: Install MongoDB
    ansible.builtin.dnf:
     name: mongodb-org
     state: present

  - name: enable MongoDB
    ansible.builtin.service:
     name: mongod
     enable: yes
     state: started

  - name: allowing remote controll
    ansible.builtin.replace:
     path: /etc/mongod.conf
     regexp: "127.0.0.1"
     replace: "0.0.0.0"

  - name: enable MongoDB
    ansible.builtin.service:
     name: mongod
     enable: yes
     state: restarted   
     